language:
  python
python:
  "2.7"
before_install:
  pip install -U pytest
install:
  pip install -r requirements.txt
env:
  global:
    - secure: "0EX6Fg79x+AkoNf0G197Y21QFUzBtpZA4BFZjhLhREeqagjJBQWzG1dw3pT5zHaixIvoLGOOY30+a+JFb/LVUvZchuOOKmIyWpBo5KboAhY5acj30x0UVeSfq35uuYxLvbjBg8hZas69D0Bhpe3mP6lULyrjGFDKBVm9OHAVIIzw+3Wxulmm3vjNNw+O1EY4DCLCyqzaEch0kQokC3Ciejt4sSBAGwgZ+DCZKkhMXXlJ/MIkxrrz2nCPa+VuivxEYMaH6/BOQsdSJRPgVrhjiNKc3DNgwSwcwwDnQrPi9dOtcTGflNVIjxRuW6i7qvjDJZQhVGE7Fo0Z5tQ251kTDdzQ/2bzyVMPt+ghmjxSseM1UUlTW/9smk9KMoEm+I6XJLcLx3Fj4eo/UZR0p0MkhDGdq1+HGuBwSyDzemWAUf0F+Szm/ADbHCKxmVJqAaXyh32rQeXT80Zh143Y10LK9qqub5H66HruVchFZPMuzrO+p+D85Y3al5wgdHqxteCRaoV5yTV6idj5LkTSaLWgImdo6hNWNd8kjYJF3DMGOHZnZHRjMd7O+kK3+lqdm+isg1igtP++tZhchng8Mv2/Z6lXKSQw+kPpemTIF3/0LjKQKxfTzsrhtecFkQXZWBrPuAqJqfGRaqyrr9NA4Ro+FboJM6PLQ3RmKjxvqfDA1pE="
    - secure: "A7SE2L1j6+q2P69I79xKsdxz8841gMXEEWaWq+YP1Hy5jE5HUqo+TLh2UXwNds65ORFAP49slZwb7jAk3KOjCJou2p7rQFCSSVj/MTNZb04SbzLQHOTQyFYo2ipLR7e83WyS1AwQhkINI2vhSiNPHC0Dheg/gxfgWYkLpi3rwjYKDU/IIoFBiQV/glpGsXz3gTMcAGUWWfCYYwPpeVC3XPTIQ0YX969apEKejn2AzfxN/bgEeUPcdF9cIAvTOwcoJk3eT8Dx9WtI7H6qekjwNUm8DBH/qwo+Hw4A60XcNY4zRwT7MqhdYuHy0lI9hepf7m2opj7PtRvn8b31n/rmWW0GEaj5lHKrcYIErF7ghAuBLPrb2KBgHiz/6WHeYlua0IcSYmlfzk2OyYU7asPuXn0AYiCwwXv9Egct3JMcyMj4gjO9mrW3d7KDwlUI6Js0D2SF/RbBF4GyR3r98jJQ/iHc4mUipg5/yh0E89qvXQpzXOP7U/CVThVrpM1iCDtC6R2jIxvKMNeelp95PUvQ3ZWkfpNuHmJhgyj87MinCXc4UEhG7VxxoAbSZPbn8HQbegh4y0Cq+qnpXC62AJlxlDxJ71LfwTmVYo2zpks9n/a4heSBAg+t1p8M9OT512jFPHO+SUbIV2fQGMmNGcXhLhuBqg/KeP8YDyRKXMFcsoU="
before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/resources/lib:$(pwd)/resources/lib/tests
script:
  pytest --rootdir=./resources/lib/tests
