language: python
python:
  - "2.7"
env:
  global:
    - secure: "Q9vVY4HIABR8q868GEvklbSQG8FdlpaHkdboxgtVkdfTAXf76Yjojj4RbmH9CXMDNJEILi+2LH8Lk3mAuNb0oFO+hobo27IJwy+dTMGzQZWuVBFFAIKoZg6tVDwYwb0GkgwFFvb+MBv61LgPJxwKak76PzBPTv5IIjK9BtXeiZ+m7IOaTbkZzxqDoK3iET1tPl9BWrQ68RTYsJFQg6YqgOhy8sxd7pp+Tto/hLyvhyS2IcESboRYfkSoiXQozXkQ2vwGsb5PJ7+CnM8Z6Km19OXeaba1hH0lvkdPomJCj5czQTn7nlbsXfL0vDnDEaea0DoSabjCQ6G5pBUVpTKfXf11On3NJ/rOuMX1D7+zI8Rdy7FgUmJYJVPPJRtRP6PZmeKaU3rDJ9VVqORO8Z1QU3ZBi4eadiTp5rsvltDW8A6T4bnCeaKJNV61QkWJR5C/VcvX0X7weiztErOO6DiXAkcUZk5aCIexldNXX1UtJvNedstoztaiJAhWHQVrV5bRG/UbTUN0ShjyNPwZM4iwR0TkMX/dv3Rn4raTfjtTWr0U1aJBPyzr72nGjLtjSRpOZ4d2c+1o3769QYsSVO34BAF1WQ4tti45ehAHhfqpTZvG/H2jv99y503+ptev17t2YFKUAYrkp2+FjqCUkUhohwCHCiTp+UniDrVucu/GBe4="
    - secure: "aLhN+b1CE92SHsZ//7Sc68kgC71oVfeQz5J+8H1evSTvvjGxmfzkrsAX4xIRYTqlyz5Y6UTGWu26nahrPUHdtORqd9+/T+UAcv5+owszZzIcGKIwX2Ut8lqWR7aiwRuyMaKKq0i1f/TP3BSNFzSHjAoG4l/ERbKsdixpvYHX4jCwZwCTE7N+xFKjde5uGDC+/4vQBGX2lh1vFlvoOMsVjvyUWmeuqhEtUFaCjf2L79IjP8LeYF976X0ZELoWhbnU0/OVUpQc4x/Cyhnww56iI4f1d/vGGTLXz7DvR+VOTB3hBFTFwtoJ7ZP88L9oQ5+S0gDd77jP4uk8j2yVE18dSBtXrELXU38BGD4cB0hmIyOmhhHK8yVLb9Q0CK8RV2f47KpAHJJ/EpiXSgQBg+EtidHxN0pbH5+jaltBdozqxwBuAhjJNZEheL5dgPz7SUS42zwK5Gu/BBz46mza+/Kete7HHinP7Uzrx7oM5tSB9oDygmwS4Bj4g8VE7LCQBbY6E92LSsN1qiXAdbnLDR5lHRnHPZlNU5XbWPibvA1eRd6lwwdrZXkD+QsGvPd/6gGup2Cp0Dfh4gQAONJ0s0FCS2qHJVPhxvOmEGh1w34krwOJRDrPljzaaUMSGA7rp9ocV011XTNDcCd3SVrk2EtlRsAJf9O8kkl3VHjx9/Ctk/Y="
    - FP_PROFILE=/tmp/plugin.video.vk
before_install:
  - pip install -U pytest
install:
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/resources/lib:$(pwd)/resources/lib/tests:$(pwd)/resources/lib/tinydb:$(pwd)/resources/lib/vk
  - mkdir -p $FP_PROFILE
script:
  - pytest --rootdir=./resources/lib/tests
# before_deploy:
deploy:
  on:
    branch: master
    tags: true
  provider: releases
  # api_key: "GITHUB OAUTH TOKEN"
  draft: true
  skip_cleanup: true
  # file: "FILE TO UPLOAD"
# after_deploy:
# after_script: