language: python
python:
- '2.7'
before_install:
- pip install -U pytest
install:
- pip install -r requirements.txt
env:
  global:
  - secure: DWmRtsCm5a4JHIHyAXrbZSWO8y2mQkYyFgE77oJ1eIOON9SBfMosMJk+oE0rxg6FMkCw/87n/8RutiY+w1UYAloK8LbLNAq7FvW3l8wAewtXP0/tG6uCOn7MhF4mL7JVohI5tCKx2eYyD7BfDrWmtG5ByE0/78uKaCxBWp3X+HWDeEY+hL9tbP7lhvY3ggKEQAHXMFgwq0Kg3K7KNEnNs0haOZoTR7dSrEMVesRfFoumrvfkuqT+YKAKyF/Sz4AiImQ++igXRGops2LOw4EnCXgXqG77zqmFUqo8az7oWMpEI72PO4iP/sW/1FBJbG5ydHjvutARNOcNKuHz7TDS9hbbimsC+xdSR+xeqYpJGbzRcCupJLjGLbUIXR6LE0++MOYb/UdCVvFhf9cf85m6vomn5QaRGD/PHlLQ4MWny5fhJ3dAb0QjSM1PSIlITuvEnObqX55DqyNxarxciCsKVRr9VBGFqvL+a3sIDk2O06ZO1DhxzoPYL8BWzaNB7yGiGZNj2c7vgu3XBa8KEBnNGFG/msV2LiGW7Lu/ggFZGkgkE7j+CKeqaYJX0f60/4emG7NzRxjIpE4hIlTs0GKs87jtaEWLQEnzfqA9l+zJRsfvXWYaxGr6pKfpMzh8TW8LbAnTwHR9SlUu2kQQvVSBVVFVWjXZ8WSOpHZOUCRiKjU=
  - secure: A7SE2L1j6+q2P69I79xKsdxz8841gMXEEWaWq+YP1Hy5jE5HUqo+TLh2UXwNds65ORFAP49slZwb7jAk3KOjCJou2p7rQFCSSVj/MTNZb04SbzLQHOTQyFYo2ipLR7e83WyS1AwQhkINI2vhSiNPHC0Dheg/gxfgWYkLpi3rwjYKDU/IIoFBiQV/glpGsXz3gTMcAGUWWfCYYwPpeVC3XPTIQ0YX969apEKejn2AzfxN/bgEeUPcdF9cIAvTOwcoJk3eT8Dx9WtI7H6qekjwNUm8DBH/qwo+Hw4A60XcNY4zRwT7MqhdYuHy0lI9hepf7m2opj7PtRvn8b31n/rmWW0GEaj5lHKrcYIErF7ghAuBLPrb2KBgHiz/6WHeYlua0IcSYmlfzk2OyYU7asPuXn0AYiCwwXv9Egct3JMcyMj4gjO9mrW3d7KDwlUI6Js0D2SF/RbBF4GyR3r98jJQ/iHc4mUipg5/yh0E89qvXQpzXOP7U/CVThVrpM1iCDtC6R2jIxvKMNeelp95PUvQ3ZWkfpNuHmJhgyj87MinCXc4UEhG7VxxoAbSZPbn8HQbegh4y0Cq+qnpXC62AJlxlDxJ71LfwTmVYo2zpks9n/a4heSBAg+t1p8M9OT512jFPHO+SUbIV2fQGMmNGcXhLhuBqg/KeP8YDyRKXMFcsoU=
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/resources/lib:$(pwd)/resources/lib/tests
- export TESTDATA_VKUSER_LOGIN=$TESTDATA_VKUSER_LOGIN
- export TESTDATA_VKUSER_PSWD=$TESTDATA_VKUSER_PSWD
script:
- pytest --rootdir=./resources/lib/tests
