language: python
python:
  - 2.7
before_install:
  - pip install -U pytest
install:
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/resources/lib:$(pwd)/resources/lib/tests
script:
  - pytest --rootdir=./resources/lib/tests
