language: python
python:
  - 2.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/resources/lib:$(pwd)/resources/lib/tests
script:
  - pytest --rootdir=./resources/lib/tests
